name: Pull Request tests

#on: [pull_request]
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        py:
          - py35
          - py36
          - py37
          - py38
          - py39
        django:
          - django-22
          - django-30
          - django-31
          - django-32
        # https://docs.djangoproject.com/en/3.2/faq/install/#what-python-version-can-i-use-with-django
        exclude:
          - django: django-22
            py: py39
          - django: django-30
            py: py35
          - django: django-31
            py: py35
          - django: django-31
            py: py36
          - django: django-32
            py: py35
          - django: django-32
            py: py36

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
#        with:
#          python-version: 3.5.4
      - name: Install Tox and any other packages
        run: pip install -r requirements_test.txt
      - name: Run Tox
        run: tox -e ${{ matrix.py }}-${{ matrix.django }}
# Codecov is running separately?
#      - name: Codecov
#        run:  codecov -e ${{ matrix.py }}-${{ matrix.django }}
